name: 'twitter_organic'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  twitter_organic_database: twitter  
  twitter_organic_schema: twitter
  account_history_staging: "{{ ref('stg_twitter__account_history') }}"
  organic_tweet_report_staging: "{{ ref('stg_twitter__organic_tweet_report') }}"
  tweet_staging: "{{ ref('stg_twitter__tweet') }}"
  users_staging: "{{ ref('stg_twitter__twitter_user_history') }}"
models:
  twitter_organic:
    +schema: twitter_organic
    +materialized: table
